version: "3"
services:
  app:
    build: ./
    container_name: Airway-Project
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://dpg-cpp1hjeehbks73bq8f40-a.oregon-postgres.render.com:5432/render_postgres_0uis"
      SPRING_DATASOURCE_USERNAME: "render_postgres_0uis_user"
      SPRING_DATASOURCE_PASSWORD: "OIZqESLGWvqbUSysz8bjiJ1ENsKb2k4I"
      UPLOAD_PATH: "/app/resources/static/images/"
      CLIENT_ID: "699864316604-976ghu6r50s3pr3os2mo6lapeme8bmsq.apps.googleusercontent.com"
      CLIENT_SECRET: "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"
      SHA512: "5627dcc7bb45a7cf9ddd211168fb727a2005338c5fe1e29faa71fc542bcd59e1bf0c604d65578ba9001984bfa0f25e29a509f130db33c51916bf0ebfbb78b645"
      SECRET_KEY: "sk_test_002fcf762bffb8f02deedfdea1e09c94fe3db328"
    volumes:
      - ./src/main/resources/:/app/resources/static/images/
    networks:
      - airway-api
    depends_on:
      - db


  db:
    image: postgres:latest
    container_name: liveairwayDB
    ports:
      - 5436:5436
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Airway
    networks:
      - airway-api


networks:
  airway-api:
    driver: bridge
