#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: "${CLIENT_ID}"
#            client-secret: "${CLIENT_SECRET}"
#  datasource:
#    username: "${SPRING_DATASOURCE_USERNAME}"
#    password: "${SPRING_DATASOURCE_PASSWORD}"
#    url: "${SPRING_DATASOURCE_URL}"
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#
#server:
#  port: 8082
#sha512:
#  string: "${SHA512}}"
#CLIENT:
#  ID: "${CLIENT_ID}"
#
## Paysatck details
#applyforme:
#  paystack:
#    secret:
#      key: "${SECRET_KEY}"
#
